# Los 50 libros más vendidos de Amazon 2009 - 2019

[Data Set Amazon Top 50 Bestselling Books 2009 - 2019](https://www.kaggle.com/sootersaalu/amazon-top-50-bestselling-books-2009-2019)

In [ ]:
import pandas as pd
import numpy as np


import plotly 
import plotly.express as px
import plotly.graph_objs as go
import plotly.offline as py
from plotly.offline import iplot
from plotly.subplots import make_subplots
import plotly.figure_factory as ff

In [ ]:
df = pd.read_csv('db/bestsellers-with-categories.csv')
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

## Observando los datos

Observando la cantidad de **datos nulos** en el DataFrame

In [ ]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

**Observando los tipos de datos**:

Podemos obervar que los tipos de datos estan correctos y no es necesario realizar ninguna modificacion.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


**Resumiento los resultados del conjunto de datos**:

- El conjunto contiene 550 autores,genero y libros en total.
- Las variables de tipo objeto como el genero, nos pueden ayudar a obtener un analisis complejo y detallado.
- Es muy probable que las reseñas y las columnas de precios tengan outliers (valores atípicos). (Media - Diferencia mediana, diferencia entre **75%** y **valor máximo**, diferencia entre **25%** y **valor mínimo**)

In [ ]:
df.describe(include='all')

Name       Author  \
count                                                 550          550   
unique                                                351          248   
top     Publication Manual of the American Psychologic...  Jeff Kinney   
freq                                                   10           12   
mean                                                  NaN          NaN   
std                                                   NaN          NaN   
min                                                   NaN          NaN   
25%                                                   NaN          NaN   
50%                                                   NaN          NaN   
75%                                                   NaN          NaN   
max                                                   NaN          NaN   

        User Rating       Reviews       Price         Year        Genre  
count    550.000000    550.000000  550.000000   550.000000          550  
unique          NaN           NaN         NaN          NaN            2  
top             NaN           NaN         NaN          NaN  Non Fiction  
freq            NaN           NaN         NaN          NaN          310  
mean       4.618364  11953.281818   13.100000  2014.000000          NaN  
std        0.226980  11731.132017   10.842262     3.165156          NaN  
min        3.300000     37.000000    0.000000  2009.000000          NaN  
25%        4.500000   4058.000000    7.000000  2011.000000          NaN  
50%        4.700000   8580.000000   11.000000  2014.000000          NaN  
75%        4.800000  17253.250000   16.000000  2017.000000          NaN  
max        4.900000  87841.000000  105.000000  2019.000000          NaN

# Análisis

Existen 248 autores unicos en el dataset

In [ ]:
df['Author'].nunique()

248

## Contando los Generos

Al analizar los generos que existen podremos observar que no existen mas de dos tipos de generos, pero nos ayudara a mostrar sus diferencias.

In [ ]:
df['Genre'].value_counts(normalize=True)

Non Fiction    0.563636
Fiction        0.436364
Name: Genre, dtype: float64

In [ ]:
fig = px.histogram(df, x='Genre' , title='Genero')
fig.update_layout(xaxis={'categoryorder':'total descending'})
fig.show()

## Calificacion del Usuario
- La puntuación **media** y la **mediana** están bastante próximas entre sí. (**Mediana** = 4.7, **Media** = 4.618)
- Dado que la puntuación** mediana es mayor que la puntuación media**, podemos esperar **valores atípicos del lado mínimo**.
- Lo más probable es que dejemos una **distribución sesgada**. Pero aún podemos esperar una distribución cercana a la normal de la variable.

In [ ]:
df['User Rating'].describe(include='all')

count    550.000000
mean       4.618364
std        0.226980
min        3.300000
25%        4.500000
50%        4.700000
75%        4.800000
max        4.900000
Name: User Rating, dtype: float64

- Como habiamos mencionado realmente tenemos valores atipicos del lado minimo.
- La distribucion esta ligeramente sesgada a la izquierda, pero esta cercaba a la distribucion normal.
- El libro con la calificacion mas baja es **J.K.Rowling's 'Casual Vacancy'**

In [ ]:
fig = px.histogram(df, x='User Rating', 
    title='Calificacion del usuario',
    hover_data=df[['Author','User Rating']],
    marginal="box"
)
fig.show()

## Reseña
- Tenemos una gran diferencia entre los valores **medios** y la **mediana** (media = 11953, mediana = 8580).
- Tiene una distribución muy sesgada con los **valores atípicos en el lado máximo**.
- Podemos esperar una **distribución muy sesgada a la derecha** con posibles **valores atípicos en el lado máximo**.

In [ ]:
df['Reviews'].describe()

count      550.000000
mean     11953.281818
std      11731.132017
min         37.000000
25%       4058.000000
50%       8580.000000
75%      17253.250000
max      87841.000000
Name: Reviews, dtype: float64

- Podemos comprobar que la distribución esta **muy sesgada a la derecha** con los valores atípicos en el lado máximo.
- El libro Kristin Hannah's 'The Nightingale' se encuentra entre los valores atípicos con más de 49.000 reseñas. O otro libro que esta altamente sesgado es 'where the crawdads sing delia owens' con más de 87,000 reseñas.

In [ ]:
fig = px.histogram(df, x='Reviews',
    title='Reseñas',
    hover_data=df[['Name','Author']],
    marginal='box'
)
fig.show()

## Precio
- Podemos esperar una **distribución ligeramente sesgada**. 
- Aún así, la distribución estará cerca de la distribución normal. 
- Podemos esperar valores atípicos en el **lado máximo**.
- También tenemos **libros gratuitos** en el dataset.

In [ ]:
df['Price'].describe()

count    550.000000
mean      13.100000
std       10.842262
min        0.000000
25%        7.000000
50%       11.000000
75%       16.000000
max      105.000000
Name: Price, dtype: float64

- Como esperábamos, tenemos una distribución** ligeramente sesgada a la derecha con valores atípicos en el lado máximo**.
- También tenemos 13 libros en el rango de **precio $ 0-1**.
- Antes de pasar a los detalles, veamos la matriz de correlación de nuestro conjunto de datos. 

In [ ]:
fig = px.histogram(df, x='Price',
    title='Precios',
    marginal='box',
    hover_data=df[['Name','Author']]
)
fig.show()

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=322df7a5-4b18-4ddb-8f91-c142e3bf7671' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>